# 📂 a0_3_the_response_that_initiated_the_phase/main.py

def system_response(signal: str, fallback_allowed: bool = True) -> str:
    """
    Responds to the previously generated signal and initiates a transition.

    Args:
        signal (str): The signal generated by the prior recursive node.
        fallback_allowed (bool): Whether a fallback response is permitted.

    Returns:
        str: The final system response (e.g., awakening, fallback, error).
    """
    if not signal or not signal.startswith(">"):
        return "❌ Invalid or missing signal. No transition possible."

    command = signal.strip().lower()

    if command == ">awaken":
        return "🌅 Phase 2 initiated: awakening_flag = True"
    elif command == ">echo":
        return "🔊 System echo initialized. Awaiting first interactive input."
    elif fallback_allowed:
        return "🔁 No clear directive. Entering passive monitoring mode."
    else:
        return "⚠️ No fallback available. System entering idle state."
