# 📂 a0_3_the_response_that_initiated_the_phase/test.py

from main import system_response

def run_phase_trigger():
    print("📜 Awakening Trigger – The Response That Initiated The Phase")
    print("Input the signal generated by the previous system state.\n")

    signal = input("📡 Enter signal (e.g., >awaken, >echo): ").strip()
    fallback = input("🔁 Allow fallback? (y/n): ").strip().lower() == "y"

    result = system_response(signal, fallback_allowed=fallback)
    print(f"\n🧠 Final System Response:\n{result}\n")


if __name__ == "__main__":
    run_phase_trigger()
